### ISSUE TITLE
housekeeping discussion: add virus total github action

### ISSUE THREAD

**Issue by dpvreony** [reactiveui/ReactiveUI#2771]
**Is your feature request related to a problem? Please describe.**
Relates to #2765
False positives on Fody etc. whether it would help for the build \ release action to be giving heads up of false positives and\or give confidence in process and potentially reduce surface scope for bad PR's especially with source generators.

- Is it wanted?
- Should it run on CI and \ or release?
- Do we want to clone an action to the org, or use direct?

Quick summary
* There is an action at https://github.com/crazy-max/ghaction-virustotal
* It supports CI and Release
* A release action may need the current release action to be marked as draft then published so the packages are on the release at the time the second action is triggered?
* It needs a virus total api key on the org

A CI action would look like

```
    - name: VirusTotal Monitor Scan
      if: ${{ env.VIRUSTOTAL_API_KEY != 0 }}
      uses: crazy-max/ghaction-virustotal@v2
      with:
        vt_api_key: ${{ env.VIRUSTOTAL_API_KEY }}
        vt_monitor: true
        monitor_path: /ghaction-virustotal
        files: |
          ./artifacts/nuget/*.nupkg
      env:
        VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
```

The release action could be a separate file and wouldn't be massively different from what is in the samples on the action page

```
name: released

on:
  release:
    types: [published]

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          github_token: ${{ github.token }}
          files: |
            .nupkg$
```
